package com.mycompany.instafitgram;

import at.favre.lib.crypto.bcrypt.BCrypt;
import com.mycompany.instafitgram.dataAcess.DataAcess;
import java.awt.Image;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class Login extends javax.swing.JFrame {

    private DataAcess dataAcess = new DataAcess();
    private Main main;

    /**
     * Creates new form Login
     */
    public Login(javax.swing.JFrame principal) {
        main = (Main) principal;
        setLocationRelativeTo(null);
        initComponents();
        ImageIcon eyeIcon = new ImageIcon("src\\main\\resources\\images\\visible.png");
        ImageIcon userIcon = new ImageIcon("src\\main\\resources\\images\\icon-user.png");
        ImageIcon passIcon = new ImageIcon("src\\main\\resources\\images\\icon-password.png");
        scaleImage(eyeIcon, lblEyeIcon);
        scaleImage(userIcon,lblUserEmail);
        scaleImage(passIcon,lblUserPass);

    }

    ////Scale a image with a label dimension
    private void scaleImage(ImageIcon icon, javax.swing.JLabel label) {
        Image img = icon.getImage();
        Image scala = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scalado = new ImageIcon(scala);
        label.setIcon(scalado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUserEmail = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        lblUserPass = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        pnlVerticalBar1 = new javax.swing.JPanel();
        pnlVerticalBar2 = new javax.swing.JPanel();
        lblEyeIcon = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(89, 174, 89));
        btnLogin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlMain.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        lblUserEmail.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblUserEmail.setForeground(new java.awt.Color(86, 86, 86));
        pnlMain.add(lblUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 20, 20));

        txtUserEmail.setActionCommand("<nonw>");
        pnlMain.add(txtUserEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 81, 186, -1));

        lblUserPass.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        lblUserPass.setForeground(new java.awt.Color(86, 86, 86));
        pnlMain.add(lblUserPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 20, 20));
        pnlMain.add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 109, 186, -1));

        pnlVerticalBar1.setBackground(new java.awt.Color(146, 240, 171));

        javax.swing.GroupLayout pnlVerticalBar1Layout = new javax.swing.GroupLayout(pnlVerticalBar1);
        pnlVerticalBar1.setLayout(pnlVerticalBar1Layout);
        pnlVerticalBar1Layout.setHorizontalGroup(
            pnlVerticalBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlVerticalBar1Layout.setVerticalGroup(
            pnlVerticalBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pnlMain.add(pnlVerticalBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlVerticalBar2.setBackground(new java.awt.Color(146, 240, 171));

        javax.swing.GroupLayout pnlVerticalBar2Layout = new javax.swing.GroupLayout(pnlVerticalBar2);
        pnlVerticalBar2.setLayout(pnlVerticalBar2Layout);
        pnlVerticalBar2Layout.setHorizontalGroup(
            pnlVerticalBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlVerticalBar2Layout.setVerticalGroup(
            pnlVerticalBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlVerticalBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, 299));

        lblEyeIcon.setToolTipText("");
        lblEyeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblEyeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEyeIconMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblEyeIconMouseReleased(evt);
            }
        });
        pnlMain.add(lblEyeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 113, 20, 18));

        btnCancel.setBackground(new java.awt.Color(204, 0, 0));
        btnCancel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pnlMain.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        User usuario = dataAcess.getUser(txtUserEmail.getText());

        if (usuario != null) {
            char[] passWordToVerify = txtUserPassword.getPassword();
            String userPassword = usuario.getPasswordHash();
            var resultado = BCrypt.verifyer().verify(passWordToVerify, userPassword);

            if (resultado.verified) {
                if (usuario.isIsIntructor()) {
                    JOptionPane.showMessageDialog(this, "Welcome!");
                    main.usuarioRegistrado(usuario);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Your are not an instructor, acess denied");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error, invalid password");
            }
        } else {
            JOptionPane.showMessageDialog(this, "User not found");
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    //Show the password
    private void lblEyeIconMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeIconMousePressed
        txtUserPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_lblEyeIconMousePressed
    //Hide the password with the char "*"
    private void lblEyeIconMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEyeIconMouseReleased
        txtUserPassword.setEchoChar('*');
    }//GEN-LAST:event_lblEyeIconMouseReleased

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
        main.setLoginVisible();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblEyeIcon;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserPass;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlVerticalBar1;
    private javax.swing.JPanel pnlVerticalBar2;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
