package com.mycompany.instafitgram;

import com.azure.storage.blob.BlobClient;
import com.azure.storage.blob.BlobClientBuilder;
import com.azure.storage.blob.BlobServiceClient;
import com.azure.storage.blob.BlobServiceClientBuilder;
import com.mycompany.instafitgram.dataAcess.DataAcess;
import com.mycompany.visualbean.SwipeListener;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaListPlayerComponent;

/**
 *
 * @author Manu
 */
public class Main extends javax.swing.JFrame {

    private User user;
    private DataAcess dataAcess = new DataAcess();
    private javax.swing.JList<Attempt> lstAttempt;
    private Review review;
    private EmbeddedMediaListPlayerComponent videoPlayer;
    private boolean isPlaying;
    private javax.swing.JDialog jdlAbout;

    private String azureConnectStr = "DefaultEndpointsProtocol=https;AccountName=simulapfileserver;AccountKey=rARWVR8b+HYR9t3Clc7SSYSKg3ziOhmItZUUdNMqSbV70r8xHhXYDw17dtNF13Ftujtj7UOZBRH5+AStTP81ig==;EndpointSuffix=core.windows.net";
    private String containerName = "simulapvideoscontainer";
    private String tempDir = System.getProperty("java.io.tmpdir");

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        videoPlayer = new EmbeddedMediaListPlayerComponent();
        pnlVideo.add(videoPlayer, BorderLayout.CENTER);
        setSize(1080, 720);
        pnlMain.setSize(1080, 720);
        setLocationRelativeTo(null);
        lstAttempt = new javax.swing.JList<>();
        scrAttempt.setViewportView(lstAttempt);
        lstAttempt.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jListAttemptComponentShown(evt);

            }
        });
        lstAttempt.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAttemptValueChanged(evt);
            }
        });

        lstAttempt.setVisible(false);
        scrAttempt.setVisible(false);

        ArrayList<User> users = dataAcess.getAllUsers();
        DefaultComboBoxModel<User> dfcm = new DefaultComboBoxModel<>();
        for (User u : users) {
            dfcm.addElement(u);
        }
        cmbUsers.setModel(dfcm);
        cmbUsers.setVisible(false);

        ImageIcon playIcon = new ImageIcon("src\\main\\resources\\images\\Play.png");
        ImageIcon pauseIcon = new ImageIcon("src\\main\\resources\\images\\Pause.png");

        scaleImage(playIcon, btnPlay);
        scaleImage(pauseIcon, btnResumePause);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        pnlVerticalBar1 = new javax.swing.JPanel();
        pnlVerticalBar2 = new javax.swing.JPanel();
        lblCorporateWebPage = new javax.swing.JLabel();
        scrAttempt = new javax.swing.JScrollPane();
        cmbUsers = new javax.swing.JComboBox<>();
        lblUsers = new javax.swing.JLabel();
        lblAttempts = new javax.swing.JLabel();
        btnShowPendingReview = new javax.swing.JButton();
        lblInfoAttemp = new javax.swing.JLabel();
        pnlVideo = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        scrComments = new javax.swing.JScrollPane();
        txaComments = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        btnResumePause = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        sldRating = new javax.swing.JSlider();
        lblRating = new javax.swing.JLabel();
        lblValorRating = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblStates = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();
        mniLogOut = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setMinimumSize(new java.awt.Dimension(1080, 720));
        pnlMain.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo.png"))); // NOI18N
        pnlMain.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 57));

        lblNombreUsuario.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreUsuario.setToolTipText("");
        pnlMain.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, 44));

        pnlVerticalBar1.setBackground(new java.awt.Color(146, 240, 171));

        javax.swing.GroupLayout pnlVerticalBar1Layout = new javax.swing.GroupLayout(pnlVerticalBar1);
        pnlVerticalBar1.setLayout(pnlVerticalBar1Layout);
        pnlVerticalBar1Layout.setHorizontalGroup(
            pnlVerticalBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        pnlVerticalBar1Layout.setVerticalGroup(
            pnlVerticalBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlVerticalBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 0, -1, 690));

        pnlVerticalBar2.setBackground(new java.awt.Color(146, 240, 171));

        javax.swing.GroupLayout pnlVerticalBar2Layout = new javax.swing.GroupLayout(pnlVerticalBar2);
        pnlVerticalBar2.setLayout(pnlVerticalBar2Layout);
        pnlVerticalBar2Layout.setHorizontalGroup(
            pnlVerticalBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlVerticalBar2Layout.setVerticalGroup(
            pnlVerticalBar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlVerticalBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 0, -1, 690));

        lblCorporateWebPage.setBackground(new java.awt.Color(255, 255, 255));
        lblCorporateWebPage.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        lblCorporateWebPage.setForeground(new java.awt.Color(204, 204, 204));
        lblCorporateWebPage.setText("www.instafitgram.com");
        lblCorporateWebPage.setToolTipText("");
        lblCorporateWebPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCorporateWebPageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCorporateWebPageMouseEntered(evt);
            }
        });
        pnlMain.add(lblCorporateWebPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));
        pnlMain.add(scrAttempt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 48, 180));

        cmbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsersActionPerformed(evt);
            }
        });
        pnlMain.add(cmbUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 220, -1, -1));

        lblUsers.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUsers.setText("Users:");
        pnlMain.add(lblUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, -1, -1));
        lblUsers.setVisible(false);

        lblAttempts.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblAttempts.setText("Attepts");
        pnlMain.add(lblAttempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));
        lblAttempts.setVisible(false);

        btnShowPendingReview.setBackground(new java.awt.Color(89, 174, 89));
        btnShowPendingReview.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnShowPendingReview.setForeground(new java.awt.Color(255, 255, 255));
        btnShowPendingReview.setText("Pendings reviews");
        btnShowPendingReview.setToolTipText("Show all pendings review that the users have");
        btnShowPendingReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPendingReviewActionPerformed(evt);
            }
        });
        pnlMain.add(btnShowPendingReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));
        btnShowPendingReview.setVisible(false);

        lblInfoAttemp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblInfoAttemp.setText("jLabel1");
        pnlMain.add(lblInfoAttemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 602, -1));
        lblInfoAttemp.setVisible(false);

        pnlVideo.setLayout(new java.awt.BorderLayout());
        pnlMain.add(pnlVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 600, 250));
        pnlVideo.setVisible(false);

        btnLogin.setBackground(new java.awt.Color(89, 174, 89));
        btnLogin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlMain.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        txaComments.setColumns(20);
        txaComments.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        txaComments.setLineWrap(true);
        txaComments.setRows(5);
        txaComments.setWrapStyleWord(true);
        scrComments.setViewportView(txaComments);

        pnlMain.add(scrComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 600, 70));
        scrComments.setVisible(false);

        btnSend.setBackground(new java.awt.Color(89, 174, 89));
        btnSend.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnSend.setForeground(new java.awt.Color(255, 255, 255));
        btnSend.setText("Send");
        btnSend.setToolTipText("Review a attempt");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        pnlMain.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));
        btnSend.setVisible(false);

        btnResumePause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pause.png"))); // NOI18N
        btnResumePause.setBorder(null);
        btnResumePause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumePauseActionPerformed(evt);
            }
        });
        pnlMain.add(btnResumePause, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 60, 40));
        btnResumePause.setVisible(false);

        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Play.png"))); // NOI18N
        btnPlay.setBorder(null);
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlMain.add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 60, 40));
        btnPlay.setVisible(false);

        sldRating.setMaximum(10);
        sldRating.setToolTipText("");
        sldRating.setValue(5);
        sldRating.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldRatingStateChanged(evt);
            }
        });
        pnlMain.add(sldRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, -1, -1));
        sldRating.setVisible(false);

        lblRating.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblRating.setText("Rating");
        pnlMain.add(lblRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));
        lblRating.setVisible(false);

        lblValorRating.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblValorRating.setText("ValorRating");
        pnlMain.add(lblValorRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, -1, -1));
        lblValorRating.setVisible(false);

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete review");
        btnDelete.setToolTipText("Delete the selected review.");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlMain.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, -1, -1));
        btnDelete.setVisible(false);

        lblStates.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblStates.setToolTipText("");
        pnlMain.add(lblStates, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, -1, -1));

        getContentPane().add(pnlMain);
        pnlMain.setBounds(0, 0, 1080, 690);

        jMenuBar1.setBackground(new java.awt.Color(202, 246, 202));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mniAbout.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        jMenu1.add(mniAbout);

        mniLogOut.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniLogOut.setText("Log out");
        mniLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mniLogOut);
        mniLogOut.setVisible(false);

        mniExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        jMenu1.add(mniExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnShowPendingReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPendingReviewActionPerformed
        ArrayList<Attempt> attempts = dataAcess.getPendingAttempts();
        DefaultListModel<Attempt> dfm = new DefaultListModel<>();
        for (Attempt u : attempts) {
            dfm.addElement(u);
        }
        lstAttempt.setModel(dfm);
        lstAttempt.setSelectedIndex(0);
    }//GEN-LAST:event_btnShowPendingReviewActionPerformed

    private void cmbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsersActionPerformed
        User user = (User) cmbUsers.getSelectedItem();
        ArrayList<Attempt> attempts = dataAcess.getAllAttemptsUser(user);
        DefaultListModel<Attempt> dfm = new DefaultListModel<>();
        for (Attempt u : attempts) {
            dfm.addElement(u);
        }
        lstAttempt.setModel(dfm);
        lstAttempt.setSelectedIndex(0);
    }//GEN-LAST:event_cmbUsersActionPerformed

    private void lblCorporateWebPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorporateWebPageMouseEntered
        lblCorporateWebPage.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblCorporateWebPageMouseEntered

    private void lblCorporateWebPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCorporateWebPageMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://www.instafitgram.com"));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblCorporateWebPageMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        Login login = new Login(this);
        login.setVisible(true);
        btnLogin.setVisible(false);
        lblWelcome.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void sldRatingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldRatingStateChanged
        sldRating.setValue(sldRating.getValue());
        lblValorRating.setText("" + sldRating.getValue());
    }//GEN-LAST:event_sldRatingStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        try {
            Review newReview = new Review(lstAttempt.getSelectedValue().getId(),
                    user.getId(), sldRating.getValue(), txaComments.getText());
            if (txaComments.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "None value added, you have to add a comment");
            } else {
                int opcion = JOptionPane.showConfirmDialog(this, "Do you want to review this attempt?",
                        "Attempt review", JOptionPane.YES_NO_OPTION);

                if (opcion == 0) {
                    //Evaluates whether the review object already exists and executes an UPDATE in the DB or if it doesn't exist, an INSERT
                    if (review.getId() != 0) {
                        review.setComent(txaComments.getText());
                        review.setReview(sldRating.getValue());
                        String mensaje = dataAcess.updateReview(review);
                        JOptionPane.showMessageDialog(this, mensaje);
                    } else {
                        String mensaje = dataAcess.setReview(newReview);
                        JOptionPane.showMessageDialog(this, mensaje);
                    }
                }

            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "None value added");
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        videoPlayer.mediaPlayer().controls().play();
        isPlaying = true;
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnResumePauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumePauseActionPerformed
        if (isPlaying) {
            videoPlayer.mediaPlayer().controls().pause();
            isPlaying = false;
        } else {
            videoPlayer.mediaPlayer().controls().start();
            isPlaying = true;
        }
    }//GEN-LAST:event_btnResumePauseActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogOutActionPerformed
        if (user != null) {
            int opcion = JOptionPane.showConfirmDialog(this, "Do you want to exit?",
                    "Log out", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                btnLogin.setVisible(true);
                lblWelcome.setVisible(true);
                lblNombreUsuario.setText("");
                user = null;
                lstAttempt.setVisible(false);
                scrAttempt.setVisible(false);
                cmbUsers.setVisible(false);
                lblInfoAttemp.setVisible(false);
                lblAttempts.setVisible(false);
                lblUsers.setVisible(false);
                btnShowPendingReview.setVisible(false);
                lblInfoAttemp.setVisible(false);
                pnlVideo.setVisible(false);
                btnPlay.setVisible(false);
                btnResumePause.setVisible(false);
                scrComments.setVisible(false);
                lblRating.setVisible(false);
                lblValorRating.setVisible(false);
                sldRating.setVisible(false);
                btnSend.setVisible(false);
                btnDelete.setVisible(false);
                lblStates.setVisible(false);
                mniLogOut.setVisible(false);
                
                

            }
        }
    }//GEN-LAST:event_mniLogOutActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        About about = new About();

        jdlAbout = new javax.swing.JDialog();
        jdlAbout.setVisible(true);
        jdlAbout.setTitle("About");
        jdlAbout.setContentPane(about);
        jdlAbout.setBounds(500, 200, 584, 384);
        jdlAbout.setLocationRelativeTo(null);

    }//GEN-LAST:event_mniAboutActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (review.getId() != 0) {
            int opcion = JOptionPane.showConfirmDialog(this, "Do you want to delete this attempt? All data will be deleted",
                    "Attempt delete", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                String mensaje = dataAcess.deleteReview(review);
                JOptionPane.showMessageDialog(this, mensaje);
                //update again the Attempts list
                User user = (User) cmbUsers.getSelectedItem();
                ArrayList<Attempt> attempts = dataAcess.getAllAttemptsUser(user);
                DefaultListModel<Attempt> dfm = new DefaultListModel<>();
                for (Attempt u : attempts) {
                    dfm.addElement(u);
                }
                lstAttempt.setModel(dfm);
                lstAttempt.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Can't delete a review that isn't created");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void jListAttemptComponentShown(java.awt.event.ComponentEvent evt) {
        ArrayList<Attempt> attempts = dataAcess.getPendingAttempts();
        DefaultListModel<Attempt> dfm = new DefaultListModel<>();
        for (Attempt u : attempts) {
            dfm.addElement(u);
        }
        lstAttempt.setModel(dfm);
        lstAttempt.setSelectedIndex(0);
    }

    public void setLoginVisible() {
        btnLogin.setVisible(true);
    }

    private void jListAttemptValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (evt.getValueIsAdjusting()) {
            return;
        }

        if (lstAttempt.getSelectedValue() != null) {
            lblInfoAttemp.setText(lstAttempt.getSelectedValue().getExercise() + " ,performed on: "
                    + lstAttempt.getSelectedValue().getTimeStampStart());
            review = dataAcess.getReviewAttempt(lstAttempt.getSelectedValue());
            txaComments.setText(review.getComent());
            sldRating.setValue(review.getReview());
            lblValorRating.setText("" + sldRating.getValue());
            lblStates.setText(review.getStatus());
            lblStates.setForeground(Color.black);
            
            if (review.getId() != 0) {

                if (review.getReview() >= 3) {
                    review.setStatus("Pass");
                    lblStates.setText(review.getStatus());
                    lblStates.setForeground(Color.green);
                } else {
                    review.setStatus("Fail");
                    lblStates.setText(review.getStatus());
                    lblStates.setForeground(Color.red);
                }
            }

            String downloadPath = tempDir + File.separator + lstAttempt.getSelectedValue().getVideoFile();
            File video = new File(downloadPath);
            //Evalue if the video exists after download it
            if (video.exists()) {

            } else {
                descargaVideo(downloadPath, lstAttempt.getSelectedValue().getVideoFile());
            }
            videoPlayer.mediaPlayer().media().prepare(downloadPath);
        } else {
        }
    }

    //Download a video from Azure Server
    public void descargaVideo(String url, String video) {
        BlobClient blobClient = new BlobClientBuilder().connectionString(azureConnectStr).
                blobName("uploaded_user_videos/" + video).
                containerName(containerName).
                buildClient();
        blobClient.downloadToFile(url);
    }

    public void usuarioRegistrado(User usuario) {
        this.user = usuario;
        lblNombreUsuario.setText("Welcome " + usuario.getNom());
        lstAttempt.setVisible(true);
        scrAttempt.setVisible(true);
        cmbUsers.setVisible(true);
        lblInfoAttemp.setVisible(true);
        lblAttempts.setVisible(true);
        lblUsers.setVisible(true);
        btnShowPendingReview.setVisible(true);

        lblInfoAttemp.setVisible(true);
        pnlVideo.setVisible(true);
        btnPlay.setVisible(true);
        btnResumePause.setVisible(true);
        scrComments.setVisible(true);
        lblRating.setVisible(true);
        lblValorRating.setVisible(true);
        sldRating.setVisible(true);
        btnSend.setVisible(true);
        btnDelete.setVisible(true);
        mniLogOut.setVisible(true);
    }

    //Scale a image with a button dimension
    private void scaleImage(ImageIcon icon, javax.swing.JButton button) {
        Image img = icon.getImage();
        Image scala = img.getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_SMOOTH);
        icon = new ImageIcon(scala);
        button.setIcon(icon);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnResumePause;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShowPendingReview;
    private javax.swing.JComboBox<User> cmbUsers;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAttempts;
    private javax.swing.JLabel lblCorporateWebPage;
    private javax.swing.JLabel lblInfoAttemp;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblStates;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblValorRating;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniLogOut;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlVerticalBar1;
    private javax.swing.JPanel pnlVerticalBar2;
    private javax.swing.JPanel pnlVideo;
    private javax.swing.JScrollPane scrAttempt;
    private javax.swing.JScrollPane scrComments;
    private javax.swing.JSlider sldRating;
    private javax.swing.JTextArea txaComments;
    // End of variables declaration//GEN-END:variables
}
